cc_library(
    name = "db_header",
    hdrs = ["db.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "cache_utils",
    hdrs = ["cache_utils.h"],
    visibility = ["//visibility:public"],
)